### ISSUE TITLE
inferior-dafny flycheck errors are misplaced when whitespace is edited

### ISSUE THREAD

**Issue by wilcoxjay** [boogie-org/boogie-friends#3] opened 2016-03-29 01:49 UTC
When there is an error in the file, adding a line of whitespace above the error causes the flycheck highlighting to incorrectly "move up" (or to incorrectly "stay put", depending on your prospective).

For example, consider the following file.

```
method Foo() returns (j: int)
  ensures j > 0
{}
```

When `inferior-dafny` checks this file, flycheck places an error on the open curly brace and a warning on the greater-than symbol. Now go to the top of the file and add a few newlines. Note that flycheck is now highlighting empty whitespace. 

This can be very confusing if you don't realize the highlighting is wrong!

**Comment by cpitclaudel** [comment] 2016-03-29 08:25
Indeed, I remember this. It's due to the way Boogie does caching. Essentially the issue is that when error messages are recycled the line numbers that they contain aren't updated. I know Rustan worked on it last summer.

@RustanLeino, do you remember if we eventually got around fixing this? (line numbers for recycled error messages?)

**Comment by cpitclaudel** [comment] 2016-04-22 15:39
Ping @RustanLeino :) (this would also be nice to fix for the CAV artifact)

**Comment by cpitclaudel** [comment] 2021-12-22 15:56
This was fixed with verifySnapshots:3

**Closed as completed by cpitclaudel** 2021-12-22 15:56 UTC
